apiVersion: apps/v1
kind: Deployment
metadata: 
  name: grounding-dino-deployment
  namespace: example
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: grounding-dino-pod # The deployment manage all pods with labels matching grounding-dino-pod
  template:
    metadata:
      labels:
        app: grounding-dino-pod # labels for all the pods the deployment is managing
    spec:
      containers:
        - name: container1
          image: duongnguyen2911/serving_grounding_dino-api:0.0.1
          resources:
            limits: # Maximum amount of a resource to be used by a container.
              memory: 1Gi
              cpu: 1
            requests: # Minimum guaranteed amount of a resource that is reserved for a container.
              memory: 1Gi
              cpu: 500m 