apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-prometheus-servicemonitor
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: http
      path: /prometheus
      interval: 15s
  selector:
    matchLabels:
      app: app