apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  namespace: model-serving
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.spec.ports.port }}
      protocol: {{ .Values.service.spec.ports.protocol }}
      targetPort: {{ .Values.service.spec.ports.targetPort }}
      nodePort: {{ .Values.service.spec.ports.nodePort }}
  type:  {{ .Values.service.spec.type }}