apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-servicemonitor
  namespace: model-serving
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: app
  namespaceSelector:
    matchNames:
      - model-serving  # or the namespace where your FastAPI service is running
  endpoints:
    - port: app-port
      path: /metrics
      interval: 10s