- name: Create a Compute Engine instance for Jenkins
  hosts: localhost
  tasks:
    - name: Start an instance
      gcp_compute_instance:
        name: jenkins-instance
        machine_type: e2-small
        zone: asia-southeast1-b # Singapore
        project: true-oasis-438103-a2
        # The service account is needed to create the resources
        auth_kind: serviceaccount
        service_account_file: ../secrets/true-oasis-438103-a2-3588212cc52d.json # replace this with your own service account private key
        disks:
          - auto_delete: true # Auto delete the disk when the VM is terminated
            boot: true # The disk contains the OS required to boot the machine 
            initialize_params:
              source_image: projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230727
              disk_size_gb: 50
        network_interfaces:
          - network:
              selfLink: global/networks/default
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT
        state: present
    
    - name: Create inbound firewall rule for port 8081 and 50000
      gcp_compute_firewall:
        name: allow-port-8081-50000
        network:
          selfLink: global/networks/default
        allowed:
          - ip_protocol: TCP
            ports: 
              - 8081
              - 50000
        source_ranges:
          - 0.0.0.0/0 # Allow traffic from any source (use a more specific source range for security)
        direction: INGRESS # Direction from outside to inside
        description: Allow incoming traffic on port 30000
        project: true-oasis-438103-a2
        auth_kind: serviceaccount
        service_account_file: ../secrets/true-oasis-438103-a2-3588212cc52d.json # replace this with your own service account private key