# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: duongnguyen2911/zero-shot-object-detection
  pullPolicy: Always
  tag: "latest"

service:
  spec:
    ports:
      port: 3000
      targetPort: 3000
      nodePort: 30001
      protocol: TCP
    type: NodePort

deployment:
  spec:
    replicas: 3
    template:
      spec:
        containers:
          ports:
            containerPort: 3000
